name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.8.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint || true
      - name: Format
        run: pnpm exec prettier --check .
      - name: Build
        run: pnpm build
      - name: Generate Supabase Types
        run: pnpm generate:types
      - name: Lighthouse Accessibility Audit
        run: |
          npm install -g lighthouse
          pnpm exec next start &
          sleep 10
          lighthouse http://localhost:3000 --only-categories=accessibility --output=json --output-path=./lighthouse-accessibility-report.json
      - name: Axe Accessibility Audit
        run: |
          pnpm exec playwright install --with-deps
          pnpm exec vitest run --testNamePattern='axe|accessibility'
      - name: Test
        run: pnpm test
